# Generated by Django 4.2.7 on 2026-02-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_car_driver_payment_usedcarinquiry_trip_reviewrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='bookings.driver'),
        ),
    ]
