# Generated by Django 4.2.7 on 2026-02-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_category',
            field=models.CharField(choices=[('affordable', 'Affordable'), ('premium', 'Premium')], default='affordable', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
