# Generated by Django 4.2.7 on 2026-02-12 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('driver_license', 'Driver License'), ('id_proof', 'ID Proof'), ('address_proof', 'Address Proof'), ('police_check', 'Police Check'), ('pan_card', 'PAN Card'), ('other', 'Other')], max_length=50)),
                ('file_path', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('expiring_soon', 'Expiring Soon')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'indexes': [models.Index(fields=['verification_status'], name='documents_verific_0b0dff_idx'), models.Index(fields=['user', 'document_type'], name='documents_user_id_588d9f_idx')],
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
